In [2]:
import pandas as pd

file_path = r"D:\-- Ayush Rana --\-- Data Analysis --\Data Analyst Projects\Zomato Bangalore Restaurants\zomato.csv"

df = pd.read_csv(file_path)

df.head(3) #Understanding the structure of dataset

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari

## Understanding Data Structure

In [ ]:
df.shape

(51717, 17)

In [ ]:
df.columns #Understanding the columns listed

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='str')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  str
 1   address                      51717 non-null  str
 2   name                         51717 non-null  str
 3   online_order                 51717 non-null  str
 4   book_table                   51717 non-null  str
 5   rate                         43942 non-null  str
 6   votes                        51717 non-null  int64
 7   phone                        50509 non-null  str
 8   location                     51696 non-null  str
 9   rest_type                    51490 non-null  str
 10  dish_liked                   23639 non-null  str
 11  cuisines                     51672 non-null  str
 12  approx_cost(for two people)  51371 non-null  str
 13  reviews_list                 51717 non-null  str
 14  menu_item                    51717 non-null  str
 15  listed_in(type)              51717 non-null  str
 16  listed_in(city)              51717 non-null  str
dtypes: int64(1), str(16)
memory usage: 552.1 MB

## Checking data quality

In [4]:
df.isnull().sum()

url                                0
address                            0
name                               0
online_order                       0
book_table                         0
rate                            7775
votes                              0
phone                           1208
location                          21
rest_type                        227
dish_liked                     28078
cuisines                          45
approx_cost(for two people)      346
reviews_list                       0
menu_item                          0
listed_in(type)                    0
listed_in(city)                    0
dtype: int64

In [5]:
df.duplicated().sum()

0

In [6]:
# Understanding the cities listed in this dataset of Bangalore Restaurants
# This are actually localities/areas and not the cities

listed_counts = (
    df.groupby("listed_in(city)")
        .size()
        .reset_index(name="count")
        .sort_values("count", ascending=False)
)

print(listed_counts)

          listed_in(city)  count
0                     BTM   3279
19  Koramangala 7th Block   2938
17  Koramangala 5th Block   2836
16  Koramangala 4th Block   2779
18  Koramangala 6th Block   2623
13              Jayanagar   2371
12               JP Nagar   2096
11            Indiranagar   1860
7           Church Street   1827
21                MG Road   1811
5            Brigade Road   1769
20           Lavelle Road   1744
10                    HSR   1741
23           Marathahalli   1659
27         Residency Road   1620
29             Whitefield   1620
2       Bannerghatta Road   1617
6             Brookefield   1518
25       Old Airport Road   1425
15           Kammanahalli   1329
14           Kalyan Nagar   1309
3            Basavanagudi   1266
28          Sarjapur Road   1261
8         Electronic City   1229
4               Bellandur   1227
9             Frazer Town   1185
22           Malleshwaram   1096
26            Rajajinagar   1079
1            Banashankari    863
24           New BEL Road    740

In [ ]:
print("Number of unique cities:", df["listed_in(city)"].nunique())  # To find the unique areas names
print(df["listed_in(city)"].unique())

Number of unique cities: 30
<ArrowStringArray>
[         'Banashankari',     'Bannerghatta Road',          'Basavanagudi',
             'Bellandur',          'Brigade Road',           'Brookefield',
                   'BTM',         'Church Street',       'Electronic City',
           'Frazer Town',                   'HSR',           'Indiranagar',
             'Jayanagar',              'JP Nagar',          'Kalyan Nagar',
          'Kammanahalli', 'Koramangala 4th Block', 'Koramangala 5th Block',
 'Koramangala 6th Block', 'Koramangala 7th Block',          'Lavelle Road',
          'Malleshwaram',          'Marathahalli',               'MG Road',
          'New BEL Road',      'Old Airport Road',           'Rajajinagar',
        'Residency Road',         'Sarjapur Road',            'Whitefield']
Length: 30, dtype: str

In [ ]:
df["name"].duplicated().sum() 

# To find the unique restaurant counts,
#so in the current table we need to consider them as outlets

42925

In [ ]:
# Restaurant and their outlet counts 

restaurants_count = (
    df.groupby("name")
        .size()
        .reset_index(name="count")
        .sort_values("count", ascending=False)
)

print(restaurants_count)

                                  name  count
1320                   Cafe Coffee Day     96
5549                            Onesta     85
3788                         Just Bake     73
2446                 Empire Restaurant     71
2577                 Five Star Chicken     70
...                                ...    ...
1900                        Cool Break      1
8076       The Shake Factory Originals      1
5216        Nethravathi Military Hotel      1
7426  Swadisht North Indian Restaurant      1
5375                Night Punjabi Folk      1

[8792 rows x 2 columns]

In [20]:
#Creating working tables 1st one is outlets

outlets = df.copy()
outlets.head(5)

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [22]:
#Adding Outlet ID and Restaurant ID

outlets["outlet_id"] = ["O" + str(i) for i in range(1, len(outlets) + 1)]

outlets["restaurant_id"] = "R" + pd.Series(
    pd.factorize(outlets["name"])[0] + 1,
    index=outlets.index
).astype(str)

In [23]:
outlets[["outlet_id", "restaurant_id", "name"]].head(10)

  outlet_id restaurant_id                                             name
0        O1            R1                                            Jalsa
1        O2            R2                                   Spice Elephant
2        O3            R3                                  San Churro Cafe
3        O4            R4                            Addhuri Udupi Bhojana
4        O5            R5                                    Grand Village
5        O6            R6                                  Timepass Dinner
6        O7            R7  Rosewood International Hotel - Bar & Restaurant
7        O8            R8                                           Onesta
8        O9            R9                                   Penthouse Cafe
9       O10           R10                                        Smacznego

In [24]:
outlets.loc[outlets["name"] == "Cafe Coffee Day", ["outlet_id", "restaurant_id", "name"]]

      outlet_id restaurant_id             name
22          O23           R22  Cafe Coffee Day
254        O255           R22  Cafe Coffee Day
625        O626           R22  Cafe Coffee Day
889        O890           R22  Cafe Coffee Day
1186      O1187           R22  Cafe Coffee Day
...         ...           ...              ...
49691    O49692           R22  Cafe Coffee Day
50119    O50120           R22  Cafe Coffee Day
50282    O50283           R22  Cafe Coffee Day
51004    O51005           R22  Cafe Coffee Day
51191    O51192           R22  Cafe Coffee Day

[96 rows x 3 columns]

In [ ]:
# Just confirming

print("Total rows:", len(outlets))
print("Unique outlet_id:", outlets["outlet_id"].nunique())
print("Unique restaurant_id:", outlets["restaurant_id"].nunique())
print("Unique names:", outlets["name"].nunique())

Total rows: 51717
Unique outlet_id: 51717
Unique restaurant_id: 8792
Unique names: 8792

In [26]:
outlets.to_csv("outlets.csv", index=False)

In [ ]:
#Checking before creating a bridge table for outlet and dish mapping

outlets["dish_liked"].isnull().sum()

28078

In [28]:
outlets["dish_liked"].sample(10)

13889                                                  NaN
9127     Burgers, Mocktails, Mashed Potato, Salads, Pas...
36977                                                  NaN
11436    Fish Fry, Crab Sukha, Chicken Biryani, Fish Cu...
22920                                                  NaN
36040    Buttermilk, Chicken Dosa, Masala Dosa, Filter ...
44920    Cappuccino, Pasta, Cucumber Spritzer, Cocktail...
29782                                                  NaN
25151    Cocktails, Peri Peri Chicken, Meat Pizza, Moji...
51232                                                  NaN
Name: dish_liked, dtype: str

In [ ]:
# Create dataframe for Outlet and dish mapping

outlet_dish_map = (
    outlets[["outlet_id", "restaurant_id", "dish_liked"]]
    .dropna(subset=["dish_liked"])
    .copy()
)

In [30]:
#Splitting each comma seperated dish names as seperate rows 

outlet_dish_map["dish_liked"] = outlet_dish_map["dish_liked"].str.split(",")
outlet_dish_map = outlet_dish_map.explode("dish_liked")
outlet_dish_map["dish_liked"] = outlet_dish_map["dish_liked"].str.strip()
outlet_dish_map = outlet_dish_map[outlet_dish_map["dish_liked"] != ""]

In [31]:
outlet_dish_map

      outlet_id restaurant_id      dish_liked
0            O1            R1           Pasta
0            O1            R1    Lunch Buffet
0            O1            R1    Masala Papad
0            O1            R1  Paneer Lajawab
0            O1            R1   Tomato Shorba
...         ...           ...             ...
51711    O51712         R2173         Biryani
51711    O51712         R2173     Andhra Meal
51715    O51716         R8788       Cocktails
51715    O51716         R8788           Pizza
51715    O51716         R8788      Buttermilk

[128848 rows x 3 columns]

In [32]:
# Creating different dishes dimension table and assigning unique id

dishes = (
    outlet_dish_map[["dish_liked"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

In [33]:
dishes["dish_id"] = ["D" + str(i) for i in range(1, len(dishes) + 1)]

In [34]:
dishes = dishes[["dish_id", "dish_liked"]]
dishes = dishes.rename(columns={"dish_liked": "dish_name"})

In [35]:
dishes

     dish_id            dish_name
0         D1                Pasta
1         D2         Lunch Buffet
2         D3         Masala Papad
3         D4       Paneer Lajawab
4         D5        Tomato Shorba
...      ...                  ...
2787   D2788           Aloo Methi
2788   D2789         Burger Combo
2789   D2790    Chicken Stromboli
2790   D2791    Chicken Pepperoni
2791   D2792  Vegetable Dumplings

[2792 rows x 2 columns]

In [ ]:
#Merging Dish ID with Outlet_Dish_map table

outlet_dish_bridge = outlet_dish_map.merge(
    dishes,
    left_on="dish_liked",
    right_on="dish_name",
    how="left"
)

In [38]:
outlet_dish_bridge = outlet_dish_bridge[
    ["outlet_id", "restaurant_id", "dish_id","dish_name"]
].drop_duplicates()

In [39]:
outlet_dish_bridge

       outlet_id restaurant_id dish_id       dish_name
0             O1            R1      D1           Pasta
1             O1            R1      D2    Lunch Buffet
2             O1            R1      D3    Masala Papad
3             O1            R1      D4  Paneer Lajawab
4             O1            R1      D5   Tomato Shorba
...          ...           ...     ...             ...
128843    O51712         R2173     D84         Biryani
128844    O51712         R2173    D313     Andhra Meal
128845    O51716         R8788    D333       Cocktails
128846    O51716         R8788     D34           Pizza
128847    O51716         R8788    D191      Buttermilk

[128848 rows x 4 columns]

In [40]:
print("Unique dishes:", dishes["dish_id"].nunique())
print("Bridge rows:", len(outlet_dish_bridge))
print("Unique outlet_ids in bridge:", outlet_dish_bridge["outlet_id"].nunique())

dishes.head()
outlet_dish_bridge.head()

Unique dishes: 2792
Bridge rows: 128848
Unique outlet_ids in bridge: 23639

  outlet_id restaurant_id dish_id       dish_name
0        O1            R1      D1           Pasta
1        O1            R1      D2    Lunch Buffet
2        O1            R1      D3    Masala Papad
3        O1            R1      D4  Paneer Lajawab
4        O1            R1      D5   Tomato Shorba

In [43]:
dishes.to_csv("dishes.csv", index=False)
outlet_dish_bridge.to_csv("outlet_dish_mapping.csv", index=False)

In [53]:
# Now same for cuisines

outlet_cuisine_mapping = (
    outlets[["outlet_id", "restaurant_id", "cuisines"]]
    .dropna(subset=["cuisines"])
    .copy()
)

In [54]:
outlet_cuisine_mapping["cuisines"] = outlet_cuisine_mapping["cuisines"].str.split(",")
outlet_cuisine_mapping = outlet_cuisine_mapping.explode("cuisines")
outlet_cuisine_mapping["cuisines"] = outlet_cuisine_mapping["cuisines"].str.strip()
outlet_cuisine_mapping = outlet_cuisine_mapping[outlet_cuisine_mapping["cuisines"] != ""]

In [55]:
outlet_cuisine_mapping

      outlet_id restaurant_id      cuisines
0            O1            R1  North Indian
0            O1            R1       Mughlai
0            O1            R1       Chinese
1            O2            R2       Chinese
1            O2            R2  North Indian
...         ...           ...           ...
51714    O51715         R8792   Finger Food
51715    O51716         R8788   Finger Food
51716    O51717         R8789   Finger Food
51716    O51717         R8789  North Indian
51716    O51717         R8789   Continental

[126819 rows x 3 columns]

In [56]:
# Creating Cuisines Dimension table

cuisines = (
    outlet_cuisine_mapping[["cuisines"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

cuisines["cuisine_id"] = ["C" + str(i) for i in range(1, len(cuisines) + 1)]

cuisines = cuisines[["cuisine_id", "cuisines"]]
cuisines = cuisines.rename(columns={"cuisines": "cuisine_name"})

In [57]:
#Merging with Outleat Cuisine mapping and cuisine dimension table

outlet_cuisine_mapping = outlet_cuisine_mapping.merge(
    cuisines,
    left_on="cuisines",
    right_on="cuisine_name",
    how="left"
)

In [58]:
outlet_cuisine_mapping = outlet_cuisine_mapping[
    ["outlet_id", "restaurant_id", "cuisine_id", "cuisine_name"]
].drop_duplicates()

In [59]:
outlet_cuisine_mapping

       outlet_id restaurant_id cuisine_id  cuisine_name
0             O1            R1         C1  North Indian
1             O1            R1         C2       Mughlai
2             O1            R1         C3       Chinese
3             O2            R2         C3       Chinese
4             O2            R2         C1  North Indian
...          ...           ...        ...           ...
126814    O51715         R8792        C49   Finger Food
126815    O51716         R8788        C49   Finger Food
126816    O51717         R8789        C49   Finger Food
126817    O51717         R8789         C1  North Indian
126818    O51717         R8789        C12   Continental

[126810 rows x 4 columns]

In [60]:
print(cuisines.head())
print(outlet_cuisine_mapping.head())
print("Unique cuisines:", cuisines["cuisine_id"].nunique())
print("Total outlet-cuisine mappings:", len(outlet_cuisine_mapping))

  cuisine_id  cuisine_name
0         C1  North Indian
1         C2       Mughlai
2         C3       Chinese
3         C4          Thai
4         C5          Cafe
  outlet_id restaurant_id cuisine_id  cuisine_name
0        O1            R1         C1  North Indian
1        O1            R1         C2       Mughlai
2        O1            R1         C3       Chinese
3        O2            R2         C3       Chinese
4        O2            R2         C1  North Indian
Unique cuisines: 107
Total outlet-cuisine mappings: 126810

In [61]:
cuisines.to_csv("cuisines.csv", index=False)
outlet_cuisine_mapping.to_csv("outlet_cuisine_mapping.csv", index=False)

In [62]:
cuisines["cuisine_name"].sort_values().tolist()[:50]

['Afghan',
 'Afghani',
 'African',
 'American',
 'Andhra',
 'Arabian',
 'Asian',
 'Assamese',
 'Australian',
 'Awadhi',
 'BBQ',
 'Bakery',
 'Bar Food',
 'Belgian',
 'Bengali',
 'Beverages',
 'Bihari',
 'Biryani',
 'Bohri',
 'British',
 'Bubble Tea',
 'Burger',
 'Burmese',
 'Cafe',
 'Cantonese',
 'Charcoal Chicken',
 'Chettinad',
 'Chinese',
 'Coffee',
 'Continental',
 'Desserts',
 'Drinks Only',
 'European',
 'Fast Food',
 'Finger Food',
 'French',
 'German',
 'Goan',
 'Greek',
 'Grill',
 'Gujarati',
 'Healthy Food',
 'Hot dogs',
 'Hyderabadi',
 'Ice Cream',
 'Indian',
 'Indonesian',
 'Iranian',
 'Italian',
 'Japanese']

In [63]:
#Checking if Cuisines are 
#actually standardized or not, so we can clean that

cuisines["cuisine_name_clean"] = (
    cuisines["cuisine_name"]
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
)

In [ ]:
cuisine_duplicates = (
    cuisines.groupby("cuisine_name_clean")["cuisine_name"]
    .agg(list)
    .reset_index()
)

cuisine_duplicates = cuisine_duplicates[
    cuisine_duplicates["cuisine_name"].apply(len) > 1
]

print(cuisine_duplicates)

#There were actually no duplicates found based on spacing or formatting

Empty DataFrame
Columns: [cuisine_name_clean, cuisine_name]
Index: []

In [66]:
cuisines["cuisine_name"].nunique(), len(cuisines)

(107, 107)

In [68]:
cuisines = cuisines.drop(columns=["cuisine_name_clean"], errors="ignore")

In [ ]:
# There are some dish name or irrelevant names in cuisines, just inspecting them by outlet rows. 

pd.set_option("display.max_rows", 200)
cuisines.sort_values("cuisine_name")

    cuisine_id      cuisine_name
74         C75            Afghan
46         C47           Afghani
60         C61           African
15         C16          American
9          C10            Andhra
43         C44           Arabian
27         C28             Asian
94         C95          Assamese
77         C78        Australian
70         C71            Awadhi
44         C45               BBQ
18         C19            Bakery
87         C88          Bar Food
65         C66           Belgian
42         C43           Bengali
13         C14         Beverages
56         C57            Bihari
21         C22           Biryani
59         C60             Bohri
98         C99           British
92         C93        Bubble Tea
19         C20            Burger
81         C82           Burmese
4           C5              Cafe
90         C91         Cantonese
50         C51  Charcoal Chicken
71         C72         Chettinad
2           C3           Chinese
72         C73            Coffee
11         C12       Continental
20         C21          Desserts
69         C70       Drinks Only
17         C18          European
14         C15         Fast Food
48         C49       Finger Food
16         C17            French
100       C101            German
31         C32              Goan
85         C86             Greek
91         C92             Grill
66         C67          Gujarati
25         C26      Healthy Food
93         C94          Hot dogs
41         C42        Hyderabadi
24         C25         Ice Cream
73         C74            Indian
29         C30        Indonesian
36         C37           Iranian
6           C7           Italian
30         C31          Japanese
102       C103            Jewish
38         C39            Juices
78         C79          Kashmiri
33         C34             Kebab
54         C55            Kerala
68         C69            Konkan
28         C29            Korean
47         C48          Lebanese
76         C77          Lucknowi
58         C59     Maharashtrian
80         C81         Malaysian
105       C106           Malwani
39         C40       Mangalorean
52         C53     Mediterranean
5           C6           Mexican
51         C52    Middle Eastern
35         C36            Mithai
75         C76     Modern Indian
12         C13             Momos
96         C97         Mongolian
1           C2           Mughlai
89         C90              Naga
61         C62          Nepalese
86         C87     North Eastern
0           C1      North Indian
55         C56             Oriya
97         C98              Paan
99        C100         Pan Asian
84         C85             Parsi
10         C11             Pizza
83         C84        Portuguese
8           C9        Rajasthani
104       C105         Raw Meats
57         C58     Roast Chicken
23         C24             Rolls
101       C102           Russian
26         C27             Salad
37         C38          Sandwich
32         C33           Seafood
106       C107            Sindhi
88         C89       Singaporean
67         C68    South American
7           C8      South Indian
79         C80           Spanish
95         C96        Sri Lankan
34         C35             Steak
22         C23       Street Food
82         C83             Sushi
63         C64             Tamil
45         C46               Tea
64         C65           Tex-Mex
3           C4              Thai
49         C50           Tibetan
62         C63           Turkish
103       C104             Vegan
40         C41        Vietnamese
53         C54             Wraps

In [76]:
selected_cuisines = ["C19", "C14", "C5", "C73", "C21", "C70", "C25", "C39", "C36", "C11", "C24", "C38", "C23", "C46", "C54", "C20", "C94"]
# These are cuisines which shouldnt be in the cuisines table, semantically seached with the help of AI



filtered_outlets = (
    outlet_cuisine_mapping[outlet_cuisine_mapping["cuisine_id"].isin(selected_cuisines)]
    .merge(outlets, on=["outlet_id", "restaurant_id"], how="left")
)

filtered_outlets.head(5)

,outlet_id,restaurant_id,cuisine_id,cuisine_name,url,address,name,online_order,book_table,rate,...,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,O3,R3,C5,Cafe,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,...,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
1,O8,R8,C11,Pizza,https://www.zomato.com/bangalore/onesta-banash...,"2469, 3rd Floor, 24th Cross, Opposite BDA Comp...",Onesta,Yes,Yes,4.6/5,...,080 48653961\r\n080 48655715,Banashankari,"Casual Dining, Cafe","Farmhouse Pizza, Chocolate Banana, Virgin Moji...","Pizza, Cafe, Italian",600,"[('Rated 5.0', 'RATED\n I personally really l...",[],Cafes,Banashankari
2,O8,R8,C5,Cafe,https://www.zomato.com/bangalore/onesta-banash...,"2469, 3rd Floor, 24th Cross, Opposite BDA Comp...",Onesta,Yes,Yes,4.6/5,...,080 48653961\r\n080 48655715,Banashankari,"Casual Dining, Cafe","Farmhouse Pizza, Chocolate Banana, Virgin Moji...","Pizza, Cafe, Italian",600,"[('Rated 5.0', 'RATED\n I personally really l...",[],Cafes,Banashankari
3,O9,R9,C5,Cafe,https://www.zomato.com/bangalore/penthouse-caf...,"1, 30th Main Road, 3rd Stage, Banashankari, Ba...",Penthouse Cafe,Yes,No,4.0/5,...,+91 8884135549\r\n+91 9449449316,Banashankari,Cafe,"Pizza, Mocktails, Coffee, Nachos, Salad, Pasta...","Cafe, Italian, Continental",700,"[('Rated 3.0', ""RATED\n I had been to this pl...",[],Cafes,Banashankari
4,O10,R10,C5,Cafe,https://www.zomato.com/bangalore/smacznego-ban...,"2470, 21 Main Road, 25th Cross, Banashankari, ...",Smacznego,Yes,No,4.2/5,...,+91 9945230807\r\n+91 9743804471,Banashankari,Cafe,"Waffles, Pasta, Coleslaw Sandwich, Choco Waffl...","Cafe, Mexican, Italian, Momos, Beverages",550,"[('Rated 4.0', ""RATED\n Easy to locate\nVFM 3...",[],Cafes,Banashankari

In [ ]:
# Removing from cuisines table

remove_cuisine_ids = [
    "C19", "C14", "C5", "C73", "C21", "C70", "C25", "C39", "C36",
    "C11", "C24", "C38", "C23", "C46", "C54", "C20", "C94"
]

#inspecting what will be removed
cuisines[cuisines["cuisine_id"].isin(remove_cuisine_ids)]

   cuisine_id cuisine_name
4          C5         Cafe
10        C11        Pizza
13        C14    Beverages
18        C19       Bakery
19        C20       Burger
20        C21     Desserts
22        C23  Street Food
23        C24        Rolls
24        C25    Ice Cream
35        C36       Mithai
37        C38     Sandwich
38        C39       Juices
45        C46          Tea
53        C54        Wraps
69        C70  Drinks Only
72        C73       Coffee
93        C94     Hot dogs

In [78]:
cuisines = cuisines[~cuisines["cuisine_id"].isin(remove_cuisine_ids)].copy()

In [79]:
outlet_cuisine_mapping = outlet_cuisine_mapping[
    ~outlet_cuisine_mapping["cuisine_id"].isin(remove_cuisine_ids)
].copy()

In [80]:
print(cuisines["cuisine_id"].isin(remove_cuisine_ids).sum())
print(outlet_cuisine_mapping["cuisine_id"].isin(remove_cuisine_ids).sum())

0
0

In [87]:
remove_cuisine_names = [
    "Bakery", "Beverages", "Cafe", "Coffee", "Desserts", "Drinks Only",
    "Ice Cream", "Juices", "Mithai", "Pizza", "Rolls", "Sandwich",
    "Street Food", "Tea", "Wraps", "Burger", "Hot dogs", "Momos", "Salad", "Finger Food",
    "Healthy Food", "Steak", "Bar Food", "Bubble Tea", "Grill",
    "Roast Chicken", "Paan", "Raw Meats", "Charcoal Chicken", "Vegan"
]

cuisines[cuisines["cuisine_name"].isin(remove_cuisine_names)].sort_values("cuisine_name")

    cuisine_id      cuisine_name
87         C88          Bar Food
92         C93        Bubble Tea
50         C51  Charcoal Chicken
48         C49       Finger Food
91         C92             Grill
25         C26      Healthy Food
12         C13             Momos
97         C98              Paan
104       C105         Raw Meats
57         C58     Roast Chicken
26         C27             Salad
34         C35             Steak
103       C104             Vegan

In [88]:
cuisines = cuisines[~cuisines["cuisine_name"].isin(remove_cuisine_names)].copy()

outlet_cuisine_mapping = outlet_cuisine_mapping[
    ~outlet_cuisine_mapping["cuisine_name"].isin(remove_cuisine_names)
].copy()

In [89]:
cuisines[cuisines["cuisine_name"].isin(remove_cuisine_names)]
outlet_cuisine_mapping[outlet_cuisine_mapping["cuisine_name"].isin(remove_cuisine_names)]

Empty DataFrame
Columns: [outlet_id, restaurant_id, cuisine_id, cuisine_name]
Index: []

In [90]:
# Exporting new data

cuisines.to_csv("cuisines.csv", index=False)
outlet_cuisine_mapping.to_csv("outlet_cuisine_mapping.csv", index=False)

In [91]:
# Analysing how many outlets counts for each cuisine

cuisine_outlet_counts = (
    outlet_cuisine_mapping
    .groupby("cuisine_name")["outlet_id"]
    .nunique()
    .reset_index(name="outlet_count")
    .sort_values("outlet_count", ascending=False)
)

In [92]:
cuisine_outlet_counts

      cuisine_name  outlet_count
56    North Indian         21085
20         Chinese         15547
67    South Indian          8644
23       Fast Food          8092
14         Biryani          6492
21     Continental          5765
33         Italian          3389
63         Seafood          1810
4           Andhra          1760
52         Mughlai          1570
3         American          1461
38          Kerala          1454
6            Asian          1295
5          Arabian          1099
37           Kebab          1036
73            Thai          1000
10             BBQ           736
22        European           715
46     Mangalorean           688
12         Bengali           575
47   Mediterranean           555
48         Mexican           539
74         Tibetan           349
34        Japanese           349
29      Hyderabadi           330
19       Chettinad           206
61      Rajasthani           183
41        Lebanese           175
76      Vietnamese           172
50   Modern Indian           155
40          Korean           143
43   Maharashtrian           139
57           Oriya           135
26            Goan           114
44       Malaysian           109
49  Middle Eastern           106
28        Gujarati           102
31      Indonesian           101
75         Turkish            92
13          Bihari            92
54        Nepalese            87
24          French            87
39          Konkan            81
0           Afghan            64
55   North Eastern            57
42        Lucknowi            55
17         Burmese            55
72         Tex-Mex            52
65     Singaporean            47
70           Sushi            46
68         Spanish            46
27           Greek            38
36        Kashmiri            33
32         Iranian            29
9           Awadhi            29
59           Parsi            29
7         Assamese            26
53            Naga            25
66  South American            20
2          African            17
69      Sri Lankan            15
51       Mongolian            12
60      Portuguese            11
1          Afghani             8
71           Tamil             7
16         British             7
25          German             7
18       Cantonese             6
62         Russian             6
15           Bohri             6
35          Jewish             6
8       Australian             5
64          Sindhi             4
11         Belgian             4
58       Pan Asian             3
30          Indian             2
45         Malwani             2

In [94]:
outlet_cuisine_mapping[outlet_cuisine_mapping["cuisine_name"] == "Indian"] \
    .merge(outlets, on=["outlet_id", "restaurant_id"], how="left")[
        ["outlet_id", "restaurant_id", "name", "location", "cuisine_name", "cuisines"]
    ]

,outlet_id,restaurant_id,name,location,cuisine_name,cuisines
0,O2756,R1579,SLV Ragigudda,Jayanagar,Indian,"South Indian, Indian"
1,O8770,R1579,SLV Ragigudda,Jayanagar,Indian,"South Indian, Indian"

In [97]:
# Analysing Liked Dish Outlets

dish_outlet_counts = (
    outlet_dish_bridge
    .groupby("dish_name")["outlet_id"]
    .nunique()
    .reset_index(name="outlet_count")
    .sort_values("outlet_count", ascending=False)
)

In [ ]:
dish_outlet_counts

# Pasta, followed by Burgers and Cocktails, 
# are the most frequently occurring items in the Liked Dishes category field, 
# appearing across 3409, 3024, and 2832 outlets respectively.

#This suggests these items have broad popularity or visibility
# across Bangalore outlets on Zomato, though this should 
# not be interpreted as direct proof of city-wide consumption or sales preference.

            dish_name  outlet_count
2030            Pasta          3409
327           Burgers          3024
822         Cocktails          2832
2124            Pizza          2737
255           Biryani          2092
...               ...           ...
2508   Supreme Burger             1
998         Doi Murgi             1
2520        Sweet Dal             1
984   Dessert Platter             1
1016  Drums Of Heaven             1

[2792 rows x 2 columns]

In [99]:
# In main Outlets data frame, cleaning rate column

outlets["rate"] = pd.to_numeric(
    outlets["rate"].str.replace("/5", "", regex=False),
    errors="coerce"
)

In [100]:
outlets["rate"].head(10)
outlets["rate"].dtype

dtype('float64')

In [102]:
outlets

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city),outlet_id,restaurant_id
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari,O1,R1
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari,O2,R2
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari,O3,R3
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari,O4,R4
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari,O5,R5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51712,https://www.zomato.com/bangalore/best-brews-fo...,"Four Points by Sheraton Bengaluru, 43/3, White...",Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6,27,080 40301477,Whitefield,Bar,NaN,Continental,"1,500","[('Rated 5.0', ""RATED\n Food and service are ...",[],Pubs and bars,Whitefield,O51713,R8728
51713,https://www.zomato.com/bangalore/vinod-bar-and...,"Number 10, Garudachar Palya, Mahadevapura, Whi...",Vinod Bar And Restaurant,No,No,NaN,0,+91 8197675843,Whitefield,Bar,NaN,Finger Food,600,[],[],Pubs and bars,Whitefield,O51714,R8733
51714,https://www.zomato.com/bangalore/plunge-sherat...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,0,NaN,Whitefield,Bar,NaN,Finger Food,"2,000",[],[],Pubs and bars,Whitefield,O51715,R8792
51715,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500","[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield,O51716,R8788
51716,https://www.zomato.com/bangalore/the-nest-the-...,"ITPL Main Road, KIADB Export Promotion Industr...",The Nest - The Den Bengaluru,No,No,3.4,13,+91 8071117272,"ITPL Main Road, Whitefield","Bar, Casual Dining",NaN,"Finger Food, North Indian, Continental","1,500","[('Rated 5.0', 'RATED\n Great ambience , look...",[],Pubs and bars,Whitefield,O51717,R8789

In [103]:
# Creating mapping table for Restaurant type and outlet 

outlet_restaurant_type_mapping = (
    outlets[["outlet_id", "restaurant_id", "rest_type"]]
    .dropna(subset=["rest_type"])
    .copy()
)

In [106]:
# Splitting comma seperated values

outlet_restaurant_type_mapping["rest_type"] = outlet_restaurant_type_mapping["rest_type"].str.split(",")
outlet_restaurant_type_mapping = outlet_restaurant_type_mapping.explode("rest_type")
outlet_restaurant_type_mapping["rest_type"] = outlet_restaurant_type_mapping["rest_type"].str.strip()
outlet_restaurant_type_mapping = outlet_restaurant_type_mapping[
    outlet_restaurant_type_mapping["rest_type"] != ""
]

In [ ]:
restaurant_types = (
    outlet_restaurant_type_mapping[["rest_type"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

restaurant_types["restaurant_type_id"] = [
    "RT" + str(i) for i in range(1, len(restaurant_types) + 1)
]

restaurant_types = restaurant_types[["restaurant_type_id", "rest_type"]]
restaurant_types = restaurant_types.rename(columns={"rest_type": "restaurant_type_name"})

In [108]:
# Mapping IDs back to Mapping table

outlet_restaurant_type_mapping = outlet_restaurant_type_mapping.merge(
    restaurant_types,
    left_on="rest_type",
    right_on="restaurant_type_name",
    how="left"
)

In [109]:
outlet_restaurant_type_mapping = outlet_restaurant_type_mapping[
    ["outlet_id", "restaurant_id", "restaurant_type_id", "restaurant_type_name"]
].drop_duplicates()

In [110]:
outlet_restaurant_type_mapping

      outlet_id restaurant_id restaurant_type_id restaurant_type_name
0            O1            R1                RT1        Casual Dining
1            O2            R2                RT1        Casual Dining
2            O3            R3                RT2                 Cafe
3            O3            R3                RT1        Casual Dining
4            O4            R4                RT3          Quick Bites
...         ...           ...                ...                  ...
59212    O51714         R8733               RT13                  Bar
59213    O51715         R8792               RT13                  Bar
59214    O51716         R8788               RT13                  Bar
59215    O51717         R8789               RT13                  Bar
59216    O51717         R8789                RT1        Casual Dining

[59217 rows x 4 columns]

In [111]:
print(restaurant_types.head())
print(outlet_restaurant_type_mapping.head())
print("Unique restaurant types:", restaurant_types["restaurant_type_id"].nunique())
print("Total outlet-restaurant type mappings:", len(outlet_restaurant_type_mapping))

  restaurant_type_id restaurant_type_name
0                RT1        Casual Dining
1                RT2                 Cafe
2                RT3          Quick Bites
3                RT4             Delivery
4                RT5                 Mess
  outlet_id restaurant_id restaurant_type_id restaurant_type_name
0        O1            R1                RT1        Casual Dining
1        O2            R2                RT1        Casual Dining
2        O3            R3                RT2                 Cafe
3        O3            R3                RT1        Casual Dining
4        O4            R4                RT3          Quick Bites
Unique restaurant types: 25
Total outlet-restaurant type mappings: 59217

In [112]:
restaurant_types.to_csv("restaurant_types.csv", index=False)
outlet_restaurant_type_mapping.to_csv("outlet_restaurant_type_mapping.csv", index=False)

In [ ]:
restaurant_types.sort_values(by="restaurant_type_name", ascending=True)

# Note:
# The `rest_type` field is not limited to dining-style categories only.
# It contains a mix of restaurant formats, service models, and outlet/shop types.
# For example:
# - Dining formats: Casual Dining, Fine Dining, Cafe, Pub
# - Service models: Delivery, Takeaway
# - Shop/outlet types: Beverage Shop, Sweet Shop, Meat Shop, Kiosk
#
# So `rest_type` should be interpreted as a broader business/outlet format field,
# not strictly as a pure restaurant-type classification.

   restaurant_type_id restaurant_type_name
6                 RT7               Bakery
12               RT13                  Bar
10               RT11        Beverage Shop
22               RT23           Bhojanalya
1                 RT2                 Cafe
0                 RT1        Casual Dining
20               RT21                 Club
13               RT14        Confectionery
3                 RT4             Delivery
5                 RT6       Dessert Parlor
19               RT20                Dhaba
9                RT10          Fine Dining
18               RT19           Food Court
15               RT16           Food Truck
21               RT22          Irani Cafee
14               RT15                Kiosk
17               RT18               Lounge
24               RT25            Meat Shop
4                 RT5                 Mess
16               RT17         Microbrewery
23               RT24               Pop Up
7                 RT8                  Pub
2                 RT3          Quick Bites
11               RT12           Sweet Shop
8                 RT9             Takeaway

In [117]:
restraurant_type_outlet_counts = (
    outlet_restaurant_type_mapping
    .groupby("restaurant_type_name")["outlet_id"]
    .nunique()
    .reset_index(name="outlet_count")
    .sort_values("outlet_count", ascending=False)
)

In [118]:
restraurant_type_outlet_counts

   restaurant_type_name  outlet_count
22          Quick Bites         20639
5         Casual Dining         13057
4                  Cafe          5074
8              Delivery          4641
9        Dessert Parlor          3211
1                   Bar          2457
24             Takeaway          2157
0                Bakery          1998
2         Beverage Shop          1471
21                  Pub           950
12           Food Court           765
23           Sweet Shop           745
16               Lounge           555
11          Fine Dining           405
19         Microbrewery           390
18                 Mess           274
15                Kiosk           192
13           Food Truck            84
7         Confectionery            47
6                  Club            41
10                Dhaba            40
14          Irani Cafee            15
17            Meat Shop             4
3            Bhojanalya             3
20               Pop Up             2

In [3]:
import pandas as pd
outlets = pd.read_csv("D:\-- Ayush Rana --\-- Data Analysis --\Data Analyst Projects\Zomato Bangalore Restaurants\Tables_Created\outlets.csv")

<>:2: SyntaxWarning: invalid escape sequence '\-'
<>:2: SyntaxWarning: invalid escape sequence '\-'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_14244\1023532556.py:2: SyntaxWarning: invalid escape sequence '\-'
  outlets = pd.read_csv("D:\-- Ayush Rana --\-- Data Analysis --\Data Analyst Projects\Zomato Bangalore Restaurants\Tables_Created\outlets.csv")

In [ ]:
# Understanding the Reviews from the outlets table

outlets["reviews_list"]
pd.set_option("display.max_colwidth", None)
outlets["reviews_list"].head(1)

0    [('Rated 4.0', 'RATED\n  A beautiful place to dine in.The interiors take you back to the Mughal era. The lightings are just perfect.We went there on the occasion of Christmas and so they had only limited items available. But the taste and service was not compromised at all.The only complaint is that the breads could have been better.Would surely like to come here again.'), ('Rated 4.0', 'RATED\n  I was here for dinner with my family on a weekday. The restaurant was completely empty. Ambience is good with some good old hindi music. Seating arrangement are good too. We ordered masala papad, panner and baby corn starters, lemon and corrionder soup, butter roti, olive and chilli paratha. Food was fresh and good, service is good too. Good for family hangout.\nCheers'), ('Rated 2.0', 'RATED\n  Its a restaurant near to Banashankari BDA. Me along with few of my office friends visited to have buffet but unfortunately they only provide veg buffet. On inquiring they said this place is mostly visited by vegetarians. Anyways we ordered ala carte items which took ages to come. Food was ok ok. Definitely not visiting anymore.'), ('Rated 4.0', 'RATED\n  We went here on a weekend and one of us had the buffet while two of us took Ala Carte. Firstly the ambience and service of this place is great! The buffet had a lot of items and the good was good. We had a Pumpkin Halwa intm the dessert which was amazing. Must try! The kulchas are great here. Cheers!'), ('Rated 5.0', 'RATED\n  The best thing about the place is itÃ\x83Ã\x83Ã\x82Ã\x82Ã\x83Ã\x82Ã\x82Ã\x92s ambiance. Second best thing was yummy ? food. We try buffet and buffet food was not disappointed us.\nTest ?. ?? ?? ?? ?? ??\nQuality ?. ??????????.\nService: Staff was very professional and friendly.\n\nOverall experience was excellent.\n\nsubirmajumder85.wixsite.com'), ('Rated 5.0', 'RATED\n  Great food and pleasant ambience. Expensive but Coll place to chill and relax......\n\nService is really very very good and friendly staff...\n\nFood : 5/5\nService : 5/5\nAmbience :5/5\nOverall :5/5'), ('Rated 4.0', 'RATED\n  Good ambience with tasty food.\nCheese chilli paratha with Bhutta palak methi curry is a good combo.\nLemon Chicken in the starters is a must try item.\nEgg fried rice was also quite tasty.\nIn the mocktails, recommend "Alice in Junoon". Do not miss it.'), ('Rated 4.0', 'RATED\n  You canÃ\x83Ã\x83Ã\x82Ã\x82Ã\x83Ã\x82Ã\x82Ã\x92t go wrong with Jalsa. Never been a fan of their buffet and thus always order alacarteÃ\x83Ã\x83Ã\x82Ã\x82Ã\x83Ã\x82Ã\x82Ã\x92. Service at times can be on the slower side but food is worth the wait.'), ('Rated 5.0', 'RATED\n  Overdelighted by the service and food provided at this place. A royal and ethnic atmosphere builds a strong essence of being in India and also the quality and taste of food is truly authentic. I would totally recommend to visit this place once.'), ('Rated 4.0', 'RATED\n  The place is nice and comfortable. Food wise all jalea outlets maintain a good standard. The soya chaap was a standout dish. Clearly one of trademark dish as per me and a must try.\n\nThe only concern is the parking. It very congested and limited to just 5cars. The basement parking is very steep and makes it cumbersome'), ('Rated 4.0', 'RATED\n  The place is nice and comfortable. Food wise all jalea outlets maintain a good standard. The soya chaap was a standout dish. Clearly one of trademark dish as per me and a must try.\n\nThe only concern is the parking. It very congested and limited to just 5cars. The basement parking is very steep and makes it cumbersome'), ('Rated 4.0', 'RATED\n  The place is nice and comfortable. Food wise all jalea outlets maintain a good standard. The soya chaap was a standout dish. Clearly one of trademark dish as per me and a must try.\n\nThe only concern is the parking. It very congested and limited to just 5cars. The basement parking is very steep and makes it cumbersome')]
Name: reviews_list, dtype: str

In [ ]:
# Working on Reviews from Outlets table and creating a seperate dimension table for it

import ast
import pandas as pd

ratings_work = (
    outlets[["outlet_id", "restaurant_id", "reviews_list"]]
    .dropna(subset=["reviews_list"])
    .copy()
)

In [8]:
def parse_reviews(review_text):
    try:
        reviews = ast.literal_eval(review_text)

        if isinstance(reviews, list):
            return reviews
        
        return []
    except:
        return []

In [9]:
ratings_work["parsed_reviews"] = ratings_work["reviews_list"].apply(parse_reviews)

In [ ]:
#Seperating each review as a row

ratings = (
    ratings_work[["outlet_id", "restaurant_id", "parsed_reviews"]]
    .explode("parsed_reviews")
    .dropna(subset=["parsed_reviews"])
    .copy()
)

In [ ]:
# Splitting tuple into rate and feedback

ratings["rate"] = ratings["parsed_reviews"].apply(lambda x: x[0] if isinstance(x, tuple) and len(x) > 0 else None)
ratings["feedback"] = ratings["parsed_reviews"].apply(lambda x: x[1] if isinstance(x, tuple) and len(x) > 1 else None)

In [ ]:
# Cleaning reviews and rate

ratings["rate"] = (
    ratings["rate"]
    .str.replace("Rated", "", regex=False)
    .str.strip()
)

ratings["rate"] = pd.to_numeric(ratings["rate"], errors="coerce")

In [ ]:
# Cleaning feedback text 

ratings["feedback"] = (
    ratings["feedback"]
    .str.replace("RATED\n", "", regex=False)
    .str.strip()
)

In [14]:
# Adding rating_id

ratings = ratings.drop(columns=["parsed_reviews"])

ratings = ratings.reset_index(drop=True)

ratings["rating_id"] = ["RA" + str(i) for i in range(1, len(ratings) + 1)]

ratings = ratings[["rating_id", "outlet_id", "restaurant_id", "rate", "feedback"]]

In [18]:
ratings.head(2)

,rating_id,outlet_id,restaurant_id,rate,feedback
0,RA1,O1,R1,4.0,A beautiful place to dine in.The interiors take you back to the Mughal era. The lightings are just perfect.We went there on the occasion of Christmas and so they had only limited items available. But the taste and service was not compromised at all.The only complaint is that the breads could have been better.Would surely like to come here again.
1,RA2,O1,R1,4.0,"I was here for dinner with my family on a weekday. The restaurant was completely empty. Ambience is good with some good old hindi music. Seating arrangement are good too. We ordered masala papad, panner and baby corn starters, lemon and corrionder soup, butter roti, olive and chilli paratha. Food was fresh and good, service is good too. Good for family hangout.\nCheers"

In [26]:
ratings.info()

<class 'pandas.DataFrame'>
RangeIndex: 1320051 entries, 0 to 1320050
Data columns (total 5 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   rating_id      1320051 non-null  str
 1   outlet_id      1320051 non-null  str
 2   restaurant_id  1320051 non-null  str
 3   rate           1319968 non-null  float64
 4   feedback       1320051 non-null  str
dtypes: float64(1), str(4)
memory usage: 507.8 MB

In [27]:
ratings.to_csv("ratings.csv", index=False)

In [1]:
import pandas as pd
outlets = pd.read_csv("D:\-- Ayush Rana --\-- Data Analysis --\Data Analyst Projects\Zomato Bangalore Restaurants\Tables_Created\outlets.csv")

<>:2: SyntaxWarning: invalid escape sequence '\-'
<>:2: SyntaxWarning: invalid escape sequence '\-'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12636\1023532556.py:2: SyntaxWarning: invalid escape sequence '\-'
  outlets = pd.read_csv("D:\-- Ayush Rana --\-- Data Analysis --\Data Analyst Projects\Zomato Bangalore Restaurants\Tables_Created\outlets.csv")

In [2]:
# Adding Longitude & Latitude for locations and a seperate table

from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import pandas as pd

locations = (
    outlets[["location"]]
    .dropna()
    .drop_duplicates()
    .reset_index(drop=True)
)

locations["location_query"] = locations["location"] + ", Bengaluru, Karnataka, India"

In [3]:
geolocator = Nominatim(user_agent="zomato_bangalore_eda_project")

geocode = RateLimiter(
    geolocator.geocode,
    min_delay_seconds=1
)

locations["geo"] = locations["location_query"].apply(geocode)

In [4]:
# Extracting lattitude and longitude from above results

locations["latitude"] = locations["geo"].apply(lambda x: x.latitude if x else None)
locations["longitude"] = locations["geo"].apply(lambda x: x.longitude if x else None)

In [5]:
locations = locations.drop(columns=["geo"])

In [6]:
outlets = outlets.merge(
    locations[["location", "latitude", "longitude"]],
    on="location",
    how="left"
)

In [8]:
outlets.to_csv("Tables_Created/outlets.csv", index=False)
locations.to_csv("Tables_Created/locations.csv", index=False)